global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus selbst
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Blackbox Exporter
  - job_name: 'blackbox_ping'
    metrics_path: /probe
    params:
      module: [icmp_ping]
    static_configs:
      - targets:
          - 8.8.8.8
          - 1.1.1.1
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'blackbox_http_2xx'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://example.com
          - https://grafana.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  - job_name: 'blackbox_http_content'
    metrics_path: /probe
    params:
      module: [http_content_match]
    static_configs:
      - targets:
          - https://meineseite.local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115

  # Node Exporter (Linux Host oder VM)
  - job_name: 'node_exporter'
    static_configs:
      - targets:
          - 192.168.0.101:9100   # Beispiel-IP eines Linux-Servers

  # Windows Exporter
  - job_name: 'windows_exporter'
    static_configs:
      - targets:
          - 192.168.0.150:9182   # Beispiel-IP eines Windows-Servers
